[package]
name = "aardwolf-api-common"
version = "0.1.0"
edition = "2024"

[lib]
name = "aardwolf_api_common"
path = "src/lib.rs"

[dependencies]
config = "0.15.9"
serde = { version = "1.0.218", features = ["derive"] }
chrono = "0.4.40"